"""Generate a failure-case report for one sequence.

The tRNA-Phe result (F1 0.326) is this project's most important negative finding
and the README reports it as a single number. A number says a prediction was bad;
it does not say which stage was responsible, and that distinction is the whole
point of the four-gate ladder.

This walks one sequence through the pipeline and writes a report that separates
the possible causes: whether the reference structure was reachable at all
(Gate A), whether the energy model preferred something else (Gate B), whether the
solver missed the QUBO's own optimum (Gate C), and only then what the structural
accuracy was (Gate D).

    python scripts/failure_case.py trna_phe_yeast_acceptor
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from foldq.classical.vienna import dotbracket_to_pairs
from foldq.config import FoldQConfig
from foldq.pipeline import FoldQPipeline
from foldq.schemas.sequence import SequenceRecord

FIXTURES = Path("data/fixtures/curated.json")


def load_record(sequence_id: str) -> dict:
    for record in json.loads(FIXTURES.read_text())["records"]:
        if record["sequence_id"] == sequence_id:
            return record
    raise SystemExit(f"no fixture {sequence_id!r} in {FIXTURES}")


def pair_table(pairs: set[tuple[int, int]]) -> str:
    if not pairs:
        return "_none_"
    return ", ".join(f"({i},{j})" for i, j in sorted(pairs))


def stems_covering(pairs: set[tuple[int, int]], stems) -> list[str]:
    """Which candidate stems would have supplied these pairs."""
    found = []
    for stem in stems:
        stem_pairs = {(stem.i + k, stem.j - k) for k in range(stem.k)}
        if stem_pairs & pairs:
            found.append(f"i={stem.i} j={stem.j} k={stem.k}")
    return found


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sequence_id", nargs="?", default="trna_phe_yeast_acceptor")
    parser.add_argument("--solver", default="simulated_annealing")
    parser.add_argument("--output", default="results/full/failure_cases")
    args = parser.parse_args()

    fixture = load_record(args.sequence_id)
    record = SequenceRecord(
        sequence_id=fixture["sequence_id"],
        sequence=fixture["sequence"],
        source_type="curated",
    )

    config = FoldQConfig()
    pipeline = FoldQPipeline(config)
    result = pipeline.predict(record, solver=args.solver)

    known = set(dotbracket_to_pairs(fixture["known_structure"]))
    predicted = (
        set(result.best_candidate.base_pairs)
        if hasattr(result.best_candidate, "base_pairs")
        else set(dotbracket_to_pairs(result.best_candidate.dot_bracket))
    )
    vienna = set(result.reference.base_pairs)

    correct = predicted & known
    false_positive = predicted - known
    false_negative = known - predicted

    stems = pipeline.build_problem(record.sequence)
    candidate_stems = list(stems.variable_map)

    gates = result.gates
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    path = output / f"{record.sequence_id}.md"

    lines = [
        f"# Failure case: {record.sequence_id}",
        "",
        f"Generated by `scripts/failure_case.py {record.sequence_id}`.",
        "",
        f"**Source.** {fixture['source']}",
        "",
        "## Sequence",
        "",
        "```text",
        record.sequence,
        fixture["known_structure"] + "   <- reference (from the fixture)",
        result.reference.mfe_structure + "   <- ViennaRNA MFE",
        result.best_candidate.dot_bracket + "   <- FoldQ prediction",
        "```",
        "",
        f"Length {record.length} nt · {stems.num_variables} QUBO variables · "
        f"density {stems.density:.3f}",
        "",
        "## Where the failure is attributed",
        "",
        f"> {gates.attribution}",
        "",
        "| Gate | Question | Result |",
        "|---|---|---|",
        f"| A | Is the reference structure reachable from the candidate stems? | "
        f"{'yes' if gates.representable else 'NO'} "
        f"({gates.representable_fraction:.0%} of its pairs reachable) |",
        f"| B | Is the reference the QUBO's ground state? | {_tri(gates.is_qubo_ground_state)} |",
        f"| C | Did the solver reach the QUBO ground state? | "
        f"{_tri(gates.solver_found_ground_state)} |",
        f"| D | Structural accuracy after decode and rescore | "
        f"base-pair F1 {gates.base_pair_f1:.3f} |",
        "",
        _diagnosis(gates),
        "",
        "## Base pairs",
        "",
        f"- **Correct** ({len(correct)}): {pair_table(correct)}",
        f"- **False positives** ({len(false_positive)}): {pair_table(false_positive)}",
        f"- **False negatives** ({len(false_negative)}): {pair_table(false_negative)}",
        "",
        "## Stems",
        "",
        f"- Candidate stems generated: **{len(candidate_stems)}**",
        f"- Stems that could have supplied the missed pairs: "
        f"{', '.join(stems_covering(false_negative, candidate_stems)) or '_none — those pairs were never available_'}",
        f"- Stems selected that contributed wrong pairs: "
        f"{', '.join(stems_covering(false_positive, candidate_stems)) or '_none_'}",
        "",
        "## What this shows",
        "",
        _interpretation(gates, known, predicted, vienna),
        "",
    ]

    path.write_text("\n".join(lines))
    print(f"wrote {path}")
    print()
    print(f"  attribution: {gates.attribution}")
    print(
        f"  F1 {gates.base_pair_f1:.3f} · correct {len(correct)} · "
        f"FP {len(false_positive)} · FN {len(false_negative)}"
    )


def _tri(value: bool | None) -> str:
    if value is None:
        return "**indeterminate** — instance exceeds the exact solver's ceiling"
    return "yes" if value else "**NO**"


def _diagnosis(gates) -> str:
    if not gates.representable:
        return (
            "**The candidate generator is responsible.** The reference structure was "
            "not reachable from the stems that were generated, so no energy model and "
            "no optimizer could have recovered it. This is a hard ceiling."
        )
    if gates.is_qubo_ground_state is False:
        return (
            "**The energy model is responsible.** The reference structure was available "
            "to the optimizer, but the QUBO scores a different structure lower, so the "
            "optimizer was correct to reject it."
        )
    if gates.solver_found_ground_state is False:
        return (
            "**The optimizer is responsible.** The reference was both reachable and the "
            "QUBO's ground state; the solver simply did not find it."
        )
    if gates.is_qubo_ground_state is None or gates.solver_found_ground_state is None:
        return (
            "**Attribution is indeterminate.** The instance exceeds the exact solver's "
            "variable ceiling, so Gates B and C could not be decided. The accuracy below "
            "is real, but this report cannot say whether the energy model or the "
            "optimizer is responsible for it — and reporting either as the cause would "
            "be a guess."
        )
    return "**No gate failed.** The prediction matched under every check."


def _interpretation(gates, known, predicted, vienna) -> str:
    overlap_with_vienna = len(predicted & vienna)
    return (
        f"The prediction shares {len(predicted & known)} of {len(known)} reference pairs "
        f"and {overlap_with_vienna} of {len(vienna)} pairs with ViennaRNA's own MFE fold.\n\n"
        "Two things are worth separating here. Gate A passing means the structure was "
        "*available* — the candidate set was not the limitation. Whether the energy "
        "model or the optimizer then chose wrongly is exactly what Gates B and C exist "
        "to distinguish, and at this size they cannot be decided, so this report says so "
        "rather than assigning blame it cannot support.\n\n"
        "This is the regime the project is honest about: small designed structures score "
        "near 1.0, and a real 76-nt cloverleaf does not. The multiloop junction at the "
        "centre of a tRNA is precisely the many-body structure a degree-2 QUBO "
        "approximates worst."
    )


if __name__ == "__main__":
    main()
