import data from "./data.json";

export interface Reference {
  key: string;
  title: string;
  role: string;
  doi: string | null;
  url: string | null;
  crossref_verified: boolean;
  resolved_title: string | null;
  container: string | null;
  year: number | null;
  authors: string[];
  verified_on: string | null;
  note: string;
}

export interface ReferenceLibrary {
  verified_on: string;
  crossref_verified: number;
  total: number;
  references: Reference[];
}

/** The bibliography, with each DOI's Crossref verification status.
 *
 *  Generated by `scripts/verify_references.py`, never hand-edited. A citation
 *  list is where an invented identifier looks most credible, so the claim that
 *  these resolve is machine-checked and re-runnable rather than asserted. */
export const library = data as ReferenceLibrary;

export const ROLES = [...new Set(library.references.map((r) => r.role))].sort();

export function byRole(role: string | null): Reference[] {
  const rows = role ? library.references.filter((r) => r.role === role) : library.references;
  // Verified first, then alphabetical — the page's whole point is which ones resolve.
  return [...rows].sort(
    (a, b) =>
      Number(b.crossref_verified) - Number(a.crossref_verified) ||
      a.title.localeCompare(b.title),
  );
}
